spring:
  datasource:
    url: jdbc:mysql://localhost:3306/latam_mc_dec_21
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

security-jwt-expiration: 30
security-jwt-signature-key: bGF0YW0tbWFzdGVyY2FyZC1kZWMtMjAyMQ==

auth0:
  audience: https://xowl.us.auth0.com/api/v2/
  domain: xowl.us.auth0.com